[project]
name = "MindQueue"
version = "0.1.0"
description = "A minimalist productivity app"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "asyncio>=4.0.0",
    "firebase-admin>=7.2.0",
    "flet>=0.80.5",
]

[tool.flet]
entrypoint = "main.py"
target = "apk"
