[project]
name = "mind-queue"
version = "0.1.0"
description = "A minimalist productivity app built with Flet"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "flet[all]",
]

[tool.flet]
entrypoint = "main.py"
target = "apk"
